### ISSUE TITLE
Polygon drawing broken

### ISSUE THREAD

**Issue by cpaulik** [pmlrsg/GISportal#44] opened 2016-05-13 10:25 UTC
Trying to draw a polygon for plotting gets stuck in dragging the map around. This was already an issue in the past see #37 but it has returned for me int he latest master.

Tried on 

- Firefox 44.0.2
- Chrome 50.0.2661.94 (64-bit)

both on Ubuntu 14.04 with GISportal running out of a docker container.

**Comment by ojsdude** [comment] 2016-05-13 13:40
2bca1eb6efe2899e07851186dd81ef24d2e8f344 seems to be the cause for this, we had a bit of trouble with some commits recently. There should be some merges soon that will correct this. Temporary repairs will be in there though.

**Comment by bcalton** [comment] 2016-05-17 13:47
This line https://github.com/pmlrsg/GISportal/commit/a7471a4464bd9eab4c275fe68f42bf82d940b26c#diff-9277609b695515774d248623758cc7eaR461 fixes the issue, and is in master

**Closed by bcalton** 2016-05-17 13:47 UTC
